
# The log file location   
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "/var/www/html/flask_template/data/db.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Programs
    - Users
    - Courses
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Program Display"
    link: "readPrograms"
  - title: "Web Form"
    link: "createPrograms"
  - title: "Relational Table"
    link: "readCourses"
